### ISSUE TITLE
No such widget `history-substring-search-up' `history-substring-search-up' 

### ISSUE THREAD

**Issue by politicus** [zsh-users/zsh-history-substring-search#100]
I am trying to install zsh history substring search after installing syntax-highlighting.

When no text was written or when a text has been written and I use the keyboard shortcut I sat, I get the error No such widget `history-substring-search-up` or `history-substring-search-up` (depending on the keyboard shortcut I use).

Here is what the end of my .zshrc looks like : 

```
#Sourcing syntax-highlighting
source /Users/User_1/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

#Zsh substring history search key bindings
#bindkey -M emacs '^P' history-substring-search-up
#bindkey -M emacs '^N' history-substring-search-down

bindkey '^N' history-substring-search-up
bindkey '^P' history-substring-search-down
```
UP and DOWN keys do work.

**Comment by politicus** [comment]
Answer: sourcing path was not right.

**Comment by hktonylee** [comment]
My solution is to run this `omz plugin load history-substring-search`. No need to hard-coded the oh-my-zsh installation path
