### ISSUE TITLE
It does not work for substring that is in the middle of previous command

### ISSUE THREAD

**Issue by davxiao** [zsh-users/zsh-history-substring-search#102]
For example, I have two commands in history (1) "abc edf" and (2) "edf abc"
and then if I type abc and press up arrow several times, only "abc edf" will show up

**Comment by gvsteen** [comment]
I checked this using the latest dockerized version of zsh (zshusers/zsh), but I cannot reproduce it.

**Comment by guidovansteen** [comment]
I checked this using the latest dockerized version of zsh (zshusers/zsh), but I cannot reproduce it.
