### ISSUE TITLE
Feature Request: Match with prefix only

### ISSUE THREAD

**Issue by SleepyBag** [zsh-users/zsh-history-substring-search#112]
Say, I have following history:
```
python foobar.py
which python
```
And when I enter `python` and press `c-p`, `which python` matches my query. This is sometimes confusing.

So, could I have a option to match only with prefix? How do you think about this idea?

**Comment by h0adp0re** [comment]
This was also requested in #95 and a subsequent PR (#96) was filed. Consider merging your efforts.
