### ISSUE TITLE
Make it skip identical commands

### ISSUE THREAD

**Issue by theonlygusti** [zsh-users/zsh-history-substring-search#114]
It looks like running these commands:

```
$ vim file.py
$ python file.py --flags
$ vim file.py
$ python file.py
$ vim file.py
$ python file.py
$ vim file.py
$ python file.py
$ vim file.py
```

Then typing `p` and hitting up arrow shows, in order

1. `python file.py`
2. `python file.py`
3. `python file.py`
4. `python file.py --flags`

Is it possible to have it skip straight to 4 from 1, to skip duplicates of the current command line, to save the number of times you have to hit up arrow to get past identical command lines?

1. `python file.py`
2. `python file.py --flags`

**Comment by guidovansteen** [comment]
Adding ```setopt histignoredups``` to your .zshrc file will enable this behavior.
