### ISSUE TITLE
How to show more strings of history when pressing ctrl-R

### ISSUE THREAD

**Issue by chukynax** [zsh-users/zsh-history-substring-search#121]
![image](https://user-images.githubusercontent.com/31927769/120146641-0da18b00-c1ee-11eb-9e75-9561474e578d.png)

i'd like to see more strings here with ability to move UP and DOWN

**Comment by antoineco** [comment]
@chukynax the screen you're showing is from https://github.com/junegunn/fzf, this program is unrelated to zsh-history-substring-search.

**Comment by sunaku** [comment]
Thanks for catching this @antoineco! :ok_hand: Closing as unrelated issue.
