### ISSUE TITLE
How to install manually (without Brew)?

### ISSUE THREAD

**Issue by ovogel-wigital** [zsh-users/zsh-history-substring-search#126]
How do I install the plugin without Homebrew?

I tried to clone the repository and include the script to `.zshrc`. Like that:

#### 1. Clone Repository
```bash
git clone https://github.com/zsh-users/zsh-history-substring-search.git ~/.zsh/plugins/zsh-history-substring-search
```

#### 2. Source in `.zshrc`
```
source ~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```

This does not seem to work. Did I miss something or is there any other way?

Any help would be greatly appreaciated.

**Comment by guidovansteen** [comment]
It works from the docker image zshusers/zsh. So, I guess the problem occurs somewhere on your side.

**Comment by ovogel-wigital** [comment]
Ok, thanks for the quick response. I will try again.

**Comment by ovogel-wigital** [comment]
FYI. The issue was a wrong key binding. Maybe it is OS releated. `'^[[A' ` works on Mac OS but does not seem to work on Windows. I switched the binding to the suggested value and now it works.

~~bindkey '^[[A' history-substring-search-up~~
~~bindkey '^[[B' history-substring-search-down~~

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
