### ISSUE TITLE
It breaks `xsel` expansion

### ISSUE THREAD

**Issue by lilydjwg** [zsh-users/zsh-history-substring-search#13]
When pressing <kbd>Tab</kbd>, `command` will expand. `xsel` wants to fstat on stdin, and this script breaks that.

See [this superuser question](http://superuser.com/q/455708/40869) for details.

**Comment by sunaku** [comment]
I'm not able to reproduce this issue anymore (`xsel` runs fine now) in my current environment:
```
$ zsh --version
zsh 5.0.5 (x86_64-pc-linux-gnu)

$ xsel --version
xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>

$ cat /etc/issue
Ubuntu 14.10 
 \l
```

Please re-open this issue if you're still able to reproduce this problem. :cop:
