### ISSUE TITLE
History not synced accross terminals.

### ISSUE THREAD

**Issue by ysftaha** [zsh-users/zsh-history-substring-search#144]
Reproduce by executing a command in one terminal and calling history-substring-search-up in another. Does not work unless `sync` or `rehash` is executed in the later terminal first.

adding
```zsh
rehash_hook() rehash
add-zsh-hook precmd rehash_hook
```
The back searching across terminals works (default ^R) or on empty prompts...Only it isn't working for history-substring-search.

**Comment by victorchoy** [comment]
where should the above code be placed?

**Comment by darccyy** [comment]
do you have `setopt SHARE_HISTORY` in your zshrc?
