### ISSUE TITLE
Create release including `HISTORY_SUBSTRING_SEARCH_PREFIXED`

### ISSUE THREAD

**Issue by cloudlena** [zsh-users/zsh-history-substring-search#150]
I would love to use this plugin with the `HISTORY_SUBSTRING_SEARCH_PREFIXED` environment variable. However, as far as I see, the latest released/tagged version is `v1.0.2` (from 2019) which does not yet include that feature. Could we get a new release or at least a tag `v1.1.0` containing this feature?

**Comment by cloudlena** [comment]
@sunaku, what do you think?

**Comment by sunaku** [comment]
Done, published as [v1.1.0](https://github.com/zsh-users/zsh-history-substring-search/releases/tag/v1.1.0) now.  Cheers!
