### ISSUE TITLE
How to install on Ubuntu 22.04 (in WSL2) without Oh My Zsh?

### ISSUE THREAD

**Issue by tonyhomfray** [zsh-users/zsh-history-substring-search#151]
I want to install zsh-history-substring-search on my Ubuntu 22.04 install in WSL2 (Windows 10) without using Oh My Zsh.

I have tried the following:

Installed the package from here (which installs correctly)
[https://software.opensuse.org/download.html?project=shells:zsh-users:zsh-history-substring-search&package=zsh-history-substring-search](https://software.opensuse.org/download.html?project=shells:zsh-users:zsh-history-substring-search&package=zsh-history-substring-search)

Added the filepath to what I think is the correct location into my .zshrc file:
```source /usr/share/zsh-history-substring-search/zsh-history-substring-search.zsh```

Added key bindings to .zshrc

Restarted terminal

But when I type a previoius command (e.g. git) and press the up/down arrowa, it just cycles through my whole history, not that matching the command I typed.

Is is possible to install on Linux with OMZ?
Are there instructions to do so?

Thanks!

**Comment by DiogoHSS** [comment]
Does the file exists in the directory its trying to source?

Mine is in /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

**Comment by guidovansteen** [comment]
Probably something is overriding your key bindings after "source
~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
is run.

**Comment by tonyhomfray** [comment]
Thanks. I'll have a look at that.

This is on a work laptop and my employer has recently given permission to replace Windows with Ubuntu, so I'll be doing a refresh install and setting ZSH up from scratch. With that in mind, I'm happy for this issue to be closed.

Thanks both for your support.
