### ISSUE TITLE
Option to not show duplicates

### ISSUE THREAD

**Issue by eproxus** [zsh-users/zsh-history-substring-search#19]
I have the options `HIST_IGNORE_DUPS` and `HIST_FIND_NO_DUPS` set in Zsh, but the substring search plugin still shows duplicates when going back in history. Is there a way to filter out duplicates when using this plugin?

**Comment by ELLIOTTCABLE** [comment]
:+1:

**Comment by parkercoates** [comment]
For those interested in this, try adding the following code (between the scissor lines) just below the code @CWSpear linked to. It seems to be working for me, but testing and feedback would be appreciated. If it works reliably for others, maybe I'll open a pull request.

    …
    # Find all occurrences of the search query in the history file.
    #
    # (k) turns it an array of line numbers.
    #
    # (on) seems to remove duplicates, which are default
    #      options. They can be turned off by (ON).
    #
    _history_substring_search_matches=(${(kon)history[(R)(#$HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS)*${_history_substring_search_query_escaped}*]})

    # --8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--
    # Remove duplicate entries if HIST_FIND_NO_DUPS is set.
    if [[ -o HIST_FIND_NO_DUPS ]]; then
        local -A unique_matches
        for n in $_history_substring_search_matches; do
            unique_matches[${history[$n]}]="$n"
        done
        _history_substring_search_matches=(${(@no)unique_matches})
    fi
    # --8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--8<--

    #
    # Define the range of values that $_history_substring_search_match_index
    …

**Comment by jyrkij** [comment]
After a quick test seems to work for me. But this was a really quick one.

**Comment by zackelflac** [comment]
It works for me as well, thanks :+1:

**Comment by jyrkij** [comment]
Yes, thanks indeed!

**Comment by CWSpear** [comment]
Can we get a PR for this?

**Comment by CWSpear** [comment]
lol, just kidding, I see the commit. As the banana said to the doctor: I'm not peeling very well this morning.

**Comment by sunaku** [comment]
PR #41 is now merged, so this issue should be fixed now.  Please re-open if it isn't. :cop:

**Comment by CWSpear** [comment]
Works for me! You're amazing and I love you all. Thank you.

**Comment by joe9** [comment]
Do you have 'setopt HIST_IGNORE_ALL_DUPS'? I think that is what is required to fix this issue. I do not have any duplicate commands pop up when I have that option set.

The above makes me suggest that trying to filter out duplicates in zsh-history-substring-search is probably not a good idea. It is probably better suited to leave the history mechanism to deal with duplicates depending on its' setopt's. It will probably help zsh-history-substring-search avoid bloat.

**Comment by ELLIOTTCABLE** [comment]
Er, why was this reverted? HIST_IGNORE_ALL_DUPS doesn't provide the functionality I want; the pull-request does.

I don't want my history *actually modified*; I simply want to skip duplicate entries when using my `history-substring-search` keybind. |=<

**Comment by sunaku** [comment]
@ELLIOTTCABLE your concerns are now addressed in 63c4bef1901981ecec2f10624ac4c60e357b1eb0.

**Comment by ELLIOTTCABLE** [comment]
@sunaku er, as of fc7eb3c, `HIST_FIND_NO_DUPS` doesn't function as described … you reverted that functionality. Unless I'm mis-reading what you just added to the README.

How about, to fix @joe9's performance concerns; add a test for `HIST_IGNORE_ALL_DUPS`, and if it's set, then skip the deduping? (If you've configured zsh to not add duplicates to the history in the first place, then there's no reason to check):

    if [[ -o HIST_FIND_NO_DUPS ]] && [[ ! -o HIST_IGNORE_ALL_DUPS ]]; then
        local -A unique_matches
        for n in $_history_substring_search_matches; do
            unique_matches[${history[$n]}]="$n"
        done
        _history_substring_search_matches=(${(@n)unique_matches})
    fi

(I haven't tested this, just a thought.)

**Comment by sunaku** [comment]
Sure, that makes sense.  I'll add a check for `HIST_IGNORE_ALL_DUPS`.

**Comment by ELLIOTTCABLE** [comment]
Might want to add a note to the README to that effect, too. ‘If HIST_FIND_NO_DUPS, then we dedup your history; for large histories or slow machines, unset it or set HIST_IGNORE_ALL_DUPS as well to prevent slow deduping’ … help prevent situations like @joe9's.

**Comment by sunaku** [comment]
Well that's not exactly what I had in mind.  I agree with @joe9 that we shouldn't prune the entire history because ZSH is much better at doing that, via `HIST_IGNORE_ALL_DUPS`.  Instead, you have the alternative of using `HIST_FIND_NO_DUPS` which (in this plugin's implementation) will filter out duplicate _adjacent_ search results quickly (great for slow machines or large histories).

**Comment by ELLIOTTCABLE** [comment]
Oh, I mis-read the intermediary perf fix you committed. I didn't realize there was a non-pruning implementation. I like it, looks good to me, as long as users aren't getting adjacent repeats!

I think it's more of a UX thing than anything else: hitting the up-arrow (or whatever) should have *some* visible effect; and this achieves that, even if you still have to hit it several times to skip interleaved (and thus not deduped) commands.

That said: Are you sure that offering *fully deduped* matching, perhaps behind another flag or configuration, isn't a good idea? I can see where fully-unique search *while retaining accurate history* might be desirable to others.

**Comment by Vidydy** [comment]
If like me you are simply trying to find a way to remove duplicates from your zsh history, here is a function that does just that. It creates a backup file called `.zsh_history-old` beforehand.

```
function dedupHistory() {
    cp ~/.zsh_history{,-old}
    tmpFile=`mktemp`
    awk -F ";" '!seen[$2]++' ~/.zsh_history > $tmpFile
    mv $tmpFile ~/.zsh_history
}
```

Cheers!

**Comment by dangooddd** [comment]
Is it true that this plugin checks for the HIST_IGNORE_ALL_DUPS or HIST_IGNORE_DUPS before it will do something? Because HIST_IGNORE_ALL_DUPS removes duplicates only from memory, and if you set up shared history for all sessions, you will got dups in history without function like @RealVidy mention. Now i got strange behaviour: when i set HIST_IGNORE_ALL_DUPS there is dups in search, and when i unset HIST_IGNORE_ALL_DUPS, there is no dups. HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1 is not working if HIST_IGNORE_ALL_DUPS is set, so i suggest to force search only unique results if HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
