### ISSUE TITLE
Autoload script

### ISSUE THREAD

**Issue by shehzan10** [zsh-users/zsh-history-substring-search#22]
Hi.
Thanks for this code. Its fantastic.
I am a little new to zsh. One thing I noticed is that adding the commands in the readme to .zshrc does not auto load the substring search each time I open a new shell terminal.
Can you tell me how I could get it to load automatically?
Thanks!

**Comment by dmdque** [comment]
I experienced the same issue but found a fix to my problem. The bindings must be set after `set -o vi`.
