### ISSUE TITLE
Local history?

### ISSUE THREAD

**Issue by arnuschky** [zsh-users/zsh-history-substring-search#33]
I would love to have a separate search for the shared history and one for the local terminal only. (I love history-substring-search, but I find it extremely annoying to have to search through history from a totally different context)

For example, it would be great if UP searches through the local history, while CTRL-UP searches through the shared one.

I tried to implement as described here:
http://superuser.com/questions/446594/separate-up-arrow-lookback-for-local-and-global-zsh-history

but this doesn't seem to work with history-substring-search. Any pointers?

**Comment by sunaku** [comment]
Try `unsetopt share_history`.  Read [this documentation](http://zsh.sourceforge.net/Doc/Release/Options.html#History) for details. :neckbeard:
