### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by hoshsadiq** [zsh-users/zsh-history-substring-search#35]
It would be nice to get this search working based on fuzzy search too. There's already a project that achieves this but the behaviour is slightly different. See https://github.com/junegunn/fzf. It would be nice to implement fzf in this plugin.

**Comment by ELLIOTTCABLE** [comment]
Yeah, I had exactly the same thought when I tried this. Great start, but fuzzy-finding and support for prioritizing initial-word matches (i.e. complying with users' usual expectations of what typing `cd ` and then ↑ will do), would make this *amazing*.

:+1:

**Comment by qoomon** [comment]
I've just implemented it se #61

**Comment by gezalore** [comment]
Multiple word based fuzzy matching is now implemented by #80. Further improvement recommendations are welcome in a new issue.

Regarding the use case described above by @ELLIOTTCABLE, I believe https://github.com/zsh-users/zsh-autosuggestions is the appropriate plugin for that.
