### ISSUE TITLE
Recover history expanders

### ISSUE THREAD

**Issue by PythonNut** [zsh-users/zsh-history-substring-search#38]
As documented in [this post on `zsh`](http://chneukirchen.org/blog/archive/2013/03/10-fresh-zsh-tricks-you-may-not-know.html), it's annoying when history expanders fail (causing the line with broken history expanders to be lost). The author proposes a way to fix it by modifying the standard zsh widgets: 

    function _recover_line_or_else() {
      if [[ -z $BUFFER && $CONTEXT = start && $zsh_eval_context = shfunc
            && -n $ZLE_LINE_ABORTED
            && $ZLE_LINE_ABORTED != $history[$((HISTCMD-1))] ]]; then
        LBUFFER+=$ZLE_LINE_ABORTED
        unset ZLE_LINE_ABORTED
      else
        zle .$WIDGET
      fi
    }
    zle -N up-line-or-history _recover_line_or_else
    function _zle_line_finish() {
      ZLE_LINE_ABORTED=$BUFFER
    }
    zle -N zle-line-finish _zle_line_finish

* Could a similar edit be made to `zsh-history-substring-search`?
* Would this be a desirable feature to include?

**Comment by sunaku** [comment]
I don't understand how failed history expanders are lost under this plugin: when you press the down arrow key, you get back the original search query (the "history expander" as you say) you started with.

**Comment by PythonNut** [comment]
If your history expanders are broken, then `zsh` will not normally save it. If you type, say,

```bash
$ !?asjdlfasjdlkfasf
zsh: no such event: asjdlfasjdlkfasf
$
```

For me, neither <kbd>Up</kbd> or <kbd>Down</kbd> will recover `!?asjdlfasjdlkfasf`, and so I need to retype it to try again.

**Comment by sunaku** [comment]
Thanks for the demonstration.  However, it appears that ZSH itself lacks what you request, as I'm able to reproduce the unwanted behavior under `zsh -f` which simply runs ZSH without any configuration or plugins whatsoever.  Therefore, adding support for such functionality is beyond the scope of this plugin. :cop:

You may have to create your own ZSH plugin to implement the history expander recovery you desire. :sweat_smile:
