### ISSUE TITLE
Color issue when used in tmux

### ISSUE THREAD

**Issue by frdmn** [zsh-users/zsh-history-substring-search#40]
Hello,

can someone help me out with this weird issue? At the moment, my history formatting looks like this:

![bildschirmfoto 2015-02-09 um 10 13 37](https://cloud.githubusercontent.com/assets/944459/6103410/5594513a-b044-11e4-99e9-acf903cf23af.png)

When used in `tmux` however, it looks like this:

![bildschirmfoto 2015-02-09 um 10 14 38](https://cloud.githubusercontent.com/assets/944459/6103431/a2498c5c-b044-11e4-9de8-2894f55b323f.png)

Can someone tell me how to get rid of the black "matching color"? I want it to be white like in my usual zsh shell as well.

    ❯  ~  echo $HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND; echo $HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND
    bg=magenta,fg=white,bold
    bg=red,fg=white,bold

Edit: Apparently I was using the wrong $TERM in my zshrc. After adding `export TERM=xterm-256color` It's black now without `tmux` as well.

**Comment by frdmn** [comment]
Fixed!

Found this in my `.tmux.conf`:

    set-option -g default-terminal "screen-256color"

Removed it and it's working fine now, no need for `TERM=xterm-256color` in .zshrc either :)

**Comment by frdmn** [comment]
Damn, I noticed now since I got rid of the 256colors, I have quite a few issues with flickering.

I want to bring it back (in both my `.zshrc` and `.tmux.conf`, but now I struggle with the "black color problem" out of the OP again.

Here's what I did so far:

    ❯  ~  echo "$bg[magenta]$fg[white]test"
    test
    ❯  ~  echo "$bg[red]$fg[white]test"
    test

=> 

![bildschirmfoto 2015-02-10 um 14 29 29](https://cloud.githubusercontent.com/assets/944459/6127978/407966ee-b131-11e4-93ae-06c417d6a0e7.png)

I don't get it at all

**Comment by sunaku** [comment]
Are you using Ubuntu by any chance?  I have problems with the search highlight under [LX]ubuntu 14.10 where the matching region is rendered in italics instead of with a yellow background color.  In the end, I had to revert the ncurses-base package back to an earlier version to fix this problem:

```sh
wget https://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/ncurses-base_5.9+20140118-1ubuntu1_all.deb
sudo dpkg -i ncurses-base_5.9+20140118-1ubuntu1_all.deb
sudo apt-mark hold ncurses-base
```

Hope that helps. :innocent:

**Comment by frdmn** [comment]
@sunaku Crud. Totally missed your reply. 

I don't use Ubuntu, I am on OS X 10.10.3 using iTerm.app. 

Not sure if that's related to this.

**Comment by sunaku** [comment]
Please try this:

```sh
zsh -f
source zsh-history-substring-search.zsh
bindkey '^P' history-substring-search-up
```

Now type in `key` and press Control-P.

Post a screenshot here of what you see.

**Comment by frdmn** [comment]
@sunaku Wow. I just realized it's working fine now! Can't tell you what I did to fix it. Here's the screenshot anyway:

![](http://up.frd.mn/3QEYJ.png)
