### ISSUE TITLE
terminfo codes in README might not work in all cases?

### ISSUE THREAD

**Issue by aw1621107** [zsh-users/zsh-history-substring-search#53]
On iTerm2 in OS X on my laptop, the arrow keys don't trigger the search functions when they are bound to `$terminfo[kcuu1/kcud1]`, but do when they are bound to `cuu1` and `cud1`.

According to the comment [here](https://github.com/robbyrussell/oh-my-zsh/issues/2735#issuecomment-41184614), `kcuu1`/`kcud1` refer to the arrow keys on the keypad. I'm not sure if this is just something unique to laptops or something, so I'm leaving it as an issue for now.

If I get time I might investigate further and see if switching would also work for desktops/full-sized keyboards.

**Comment by sunaku** [comment]
Thanks, the README has been updated accordingly in commit 36314a13ead75c52b45c2ce6829ee9718cb95e0d. :+1:
