### ISSUE TITLE
How to uninstall this plugin

### ISSUE THREAD

**Issue by shixinzi** [zsh-users/zsh-history-substring-search#56]
hi,How to uninstall this plugin

**Comment by meritozh** [comment]
just remove `/usr/local/opt/zsh-history-substring-search`

**Comment by sunaku** [comment]
@shixinzi how did you install this plugin in the first place?
@meritozh thanks for responding.

**Comment by sunaku** [comment]
I'm closing this issue; see @meritozh's answer in https://github.com/zsh-users/zsh-history-substring-search/issues/56#issuecomment-216030668 above.
