### ISSUE TITLE
Better antigen support

### ISSUE THREAD

**Issue by marco-lavagnino** [zsh-users/zsh-history-substring-search#59]
When using antigen, you get used to `antigen bundle packagename` and get package working. To use this plugin, some keybinding is needed. 

It would be nice if running `antigen bundle zsh-users/zsh-history-substring-search` could get the plugin working, or at least leaving a note in the README for antigen users.

**Comment by Tarrasch** [comment]
@marco-lavagnino, what is missing do you think? Can you be more concrete? Is it correct the only thing you need is the keybindings?

**Comment by unixorn** [comment]
@Tarrasch This may be related to the removal of the `.plugin.zsh` file as discussed in https://github.com/zsh-users/zsh-history-substring-search/issues/48 and https://github.com/zsh-users/zsh-history-substring-search/pull/49/files.@marco-lavagnino's description sounds like Antigen is looking specifically for a `plugin.zsh` file and not checking for `*.zsh`

**Comment by desyncr** [comment]
@Tarrasch @marco-lavagnino may correct me but yes, the issue is with keybindings.

@unixorn Antigen has no issues with or without `plugin.zsh`, it will look for `*.zsh` and load it.

**Comment by sunaku** [comment]
@desyncr Thanks for clarifying. :+1:   Antigen users should just configure their keybindings (as described in step 2 of the "Usage" section in the README) after activating this plugin; it's only 2 extra lines of code. :scream:

```sh
antigen bundle zsh-users/zsh-history-substring-search
# configure your keybindings here... just 2 lines of code!
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```

**Comment by aramboi** [comment]
The `bindkey` lines above should be added after `antigen apply` in order to work.
Thanks for explaining this issue in detail @sunaku.

**Comment by sunaku** [comment]
@aramboi Thanks for confirming. :+1: Here's a final example for Antigen users:

```sh
antigen bundle zsh-users/zsh-history-substring-search
antigen apply

# zsh-history-substring-search configuration
# (put whatever configuration you want here!)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
# and more... see the README for information
```

Case closed. :closed_book:

**Comment by kapad** [comment]
```
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```
Which keyboard key combinations will this map to?

**Comment by guidovansteen** [comment]
> Which keyboard key combinations will this map to?

arrow up and arrow down.
