### ISSUE TITLE
setopt ERR_RETURN breaks this plugin

### ISSUE THREAD

**Issue by Tarrasch** [zsh-users/zsh-history-substring-search#60]
I updated my plugin and it mostly stopped working. I suspect the re-factorings @gazalore because that's the biggest changeset. At least always when I search for something like "git push<UP>" I get any kinds of git commands and not only the "git push" commands as I expect.

For my own sanity, I forked this repo so new sudden changes doesn't disrupt me as easily again. In that repo I reverted to a version which seem to work. https://github.com/Tarrasch/zsh-history-substring-search

I apologize for not providing more details, but time will tell if others will report similar issues already or not.

**Comment by gezalore** [comment]
Works for me so more detail would be helpful, which version of zsh?

**Comment by Tarrasch** [comment]
I use version 5.0.2 on Ubuntu 14.04 LTS. I have quite [many modifications](https://github.com/Tarrasch/dotfiles) which might interfere.

Here's a video illustrating the buggy behaviour: https://asciinema.org/a/dc9jjl1984n71c7jc6noy5iqm

**Comment by z0rc** [comment]
@Tarrasch can you provide minimum zshrc and set of commands to reproduce this issue?

**Comment by Tarrasch** [comment]
I don't have time at the very moment. Maybe we can let this be open for a while and see if other's report the same issue?

**Comment by mehcode** [comment]
I have the same issue. I use antigen (installed through homebrew) and my zshrc is as follows:

```
source $(brew --prefix)/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell

# Tell antigen that you're done.
antigen apply
```

I did a fresh install (OS/etc.) and this plugin does not work. On my other computer (I never update zsh plugins) it still works with an identical zshrc (just a few months older).

**Comment by Tarrasch** [comment]
@mehcode, can you change your line `antigen bundle zsh-users/zsh-syntax-highlighting` to `antigen bundle Tarrasch/zsh-syntax-highlighting`? If that resolves the issue it increases the that we actually have the same issue.

If it's the same issue. Then OS version (ubuntu vs mac) and loading library (antigen vs antigen-hs) doesn't matter.

**Comment by aramboi** [comment]
I have the same issue after a recent update, using `antigen` and zsh 5.2. My `.zshrc` is fairly basic (see https://github.com/aramboi/dotfiles/blob/master/.zshrc). 

@Tarrasch your fork does not solve the issue for me.

@mehcode I don't see `zsh-history-substring-search` in your config (which this issue is for), only `zsh-syntax-highlighting`. You should add `antigen bundle zsh-users/zsh-history-substring-search` and see if that works for you.

**Comment by aramboi** [comment]
Tested again with the following simple `.zshrc`:
```
source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-history-substring-search
antigen apply
```
The search fails for newly opened terminals. If you do `source ~/.zshrc` after opening a new terminal then it works properly for the above config.

**Comment by sunaku** [comment]
@aramboi After opening a new terminal and _before_ `source ~/.zshrc`, what output does this give you?

    type history-substring-search-up

**Comment by sunaku** [comment]
Are we certain that this isn't an Antigen issue? :scream:  I use this plugin with plain old ZSH and it works fine:

```
$ zsh -f
yantram% source zsh-history-substring-search.zsh
yantram% bindkey '^[[A' history-substring-search-up
yantram% sea<UP><UP>
```

You can watch the above output in live action at https://asciinema.org/a/e15cx9kzwr4dkmh3xk5v28y26

**Comment by Tarrasch** [comment]
@sunaku, for me at least, the issue with the new version isn't noticeable until I search for something containing a space character.

For example

    sea<c-up>

Would work as in your asciinema :movie_camera:

     source zs<c-up>

Would not find `source zsh-history-substring-....`.

----

I'm feeling some doubt that everyone are chattering about the same issue (searching with space-character) or not. :-/

**Comment by sunaku** [comment]
@Tarrasch thanks for clarifying, but again I wasn't able to produce the problem: :disappointed_relieved:
I'm able to search using spaces just fine; for example `key '` [in this screencast](https://asciinema.org/a/89738). :movie_camera:

**Comment by mindeunix** [comment]
Updated today and got some strange problems (not using antigen).

cd /usr/share<Return>
cd /dev/shm<Return>
cd /<Press-Up>
nothing happens!
cd /<Press-Up>
again, nothing.
cd /<Press-Down>
now 'cd /' is colored in red
cd /<Press-Up>
nothing.
cd /<Press-Up>
completed to /usr/share

Works with zsh -f.

**Comment by mindeunix** [comment]
Found how to reproduce this problem:
```
$ zsh -f
$ source zsh-history-substring-search.zsh
$ bindkey '^[[B' history-substring-search-down
$ bindkey '^[[A' history-substring-search-up
$ cd /usr/share
$ cd /<Press-Up>
# Works.
$ setopt ERR_RETURN
$ cd /<Press-Up>
# Fails.
```

**Comment by aramboi** [comment]
Adding the following lines to my `.zshrc` seems to solve this issue:
```
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```
For `antigen` users make sure you add them after `antigen apply`.

I don't know why this used to work before and stopped now. Maybe an `antigen` update changed the way bundles were loaded. The fix is also better explained in https://github.com/zsh-users/zsh-history-substring-search/issues/59 for `antigen` users.

**Comment by mindeunix** [comment]
> I don't know why this used to work before and stopped now. Maybe an antigen update changed the way bundles were loaded. The fix is also better explained in #59 for antigen users.

Default keybindings removed long time ago  https://github.com/zsh-users/zsh-history-substring-search/commit/82fbef5132b44c5d039e7d25972d9351c5936bc2

Anyway, **ERR_RETURN** problem still remains for me, maybe someone can reproduce?

**Comment by sunaku** [comment]
@mindeunix Confirrmed! :+1: Setting `ERR_RETURN` indeed breaks `history-substring-search-up`, and it happens for me _regardless_ of whether spaces are used in the search query:

```sh
$ zsh -f
yantram% source zsh-history-substring-search.zsh 
yantram% bindkey '^[[A' history-substring-search-up
yantram% setopt ERR_RETURN      
yantram% ce<UP> # does nothing
yantram% ce<SPACE>zsh<UP> # does nothing
```

**Comment by sunaku** [comment]
@Tarrasch Do you have `ERR_RETURN` enabled?  Can you can reproduce the problem under `zsh -f`?

**Comment by Tarrasch** [comment]
@sunaku & @mindeunix, thanks for posting such easy-to-reproduce steps. My results are:

 - Without `ERR_RETURN`: Both works
 - With `ERR_RETURN`: Neither (`ce<UP>` nor `ce<SPACE>zsh<UP>`) works.

I guess the conclusion is that I have something deep down somewhere in my zshrc making the plugin break for the space character. But generally the this plugin works for me on my machine when running with `zsh --no-rcs`.
