### ISSUE TITLE
down-key does not work

### ISSUE THREAD

**Issue by jasonkuhrt** [zsh-users/zsh-history-substring-search#63]
Platform version:

<img width="251" alt="screen shot 2016-10-18 at 10 52 19 pm" src="https://cloud.githubusercontent.com/assets/284476/19504056/8f1ba462-9585-11e6-84e3-f94dd6d88b83.png">

However this:

```
# OPTION 2: for iTerm2 running on Apple MacBook laptops
zmodload zsh/terminfo
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down
```

seems to only partially work on my system: pressing down does nothing, but pressing _up_ does work.

**Comment by jasonkuhrt** [comment]
This bug report applies to both `iterm2` and `terminal`.

**Comment by sunaku** [comment]
What output do you see when you run `cat -v` and then press up and down arrow keys?

**Comment by jasonkuhrt** [comment]
Hey, here's the result; I pressed `up` and `down`:

```
❯ cat -v
^[[A^[[B
```

**Comment by jasonkuhrt** [comment]
I solved my problem by updating my zsh configuration with the following:

```
zmodload zsh/terminfo
bindkey "$terminfo^[[A" history-substring-search-up
bindkey "$terminfo^[[B" history-substring-search-down
```

Assuming this is correct you I guess just update your documentation?

**Comment by jasonkuhrt** [comment]
Sorry, never mind. I confused myself into think what I did above worked. It does not.

**Comment by sunaku** [comment]
@jasonkuhrt Since your `cat -v` showed `^[[A` for up and `^[[B` for down, try using these settings:

```sh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```

**Comment by jasonkuhrt** [comment]
Solved! Documentation just needs tweaking then?

**Comment by sunaku** [comment]
@jasonkuhrt Yes, docs tweaked accordingly in commit 2f8a21062c0df0d5c6be8f0726655fd6e9fbd71c. :star2:

**Comment by lexinator** [comment]
i'm not dug into why but i use:
```
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```

After a quick google i found http://stackoverflow.com/questions/21175561/terminfo-smkx-and-application-cursor-keys-vs-application-keypad.  There seems to be a difference between normal mode and application mode for cursor keys.

**Comment by sunaku** [comment]
@lexinator Thanks for the background. :books:  I've seen enough reports (#12, #21, #37) about the various "portable" keycode expressions not working consistently for everyone that I'm satisfied with the experimental method outlined in the README: even though it may be unportable across _all_ terminals, it's at least :100: guaranteed to work for the user on the terminal where they observed their `cat -v` output.
