### ISSUE TITLE
Up and down key not working

### ISSUE THREAD

**Issue by hitochan777** [zsh-users/zsh-history-substring-search#64]
Hello. Up and down key seems to be not working. Whenever I press up and down key it seems that console simply shows the previous or next command relative to the currently shown command, not cycling through the matches to a given substring.

I checked `cat -v` to observe key codes for up and down key (^[[A and ^[[B for up and down key, respectively).

I use zplug to load this module together with zsh-syntax-highlighting. As instructed, I make sure that zsh-syntax-highlighting is loaded before zsh-history-substring-search.

zsh version I use is as follows:
```
$ zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

my .zshrc is available [here](https://github.com/hitochan777/dotfiles/blob/master/zshrc). Thanks in advance.

**Comment by sunaku** [comment]
Do the key codes you observed for up and down work properly without zplug?

```
$ zsh -f
yantram% source zsh-history-substring-search.zsh
yantram% bindkey '^[[A' history-substring-search-up
yantram% sea<UP><UP>
```

You can watch the above as a screencast at https://asciinema.org/a/89727 :movie_camera:

**Comment by hitochan777** [comment]
@sunaku I tried and it works!! So zplug is doing something nasty?

**Comment by sunaku** [comment]
Yes, try moving your `bindkey` definitions above the `zplug load` line. :balloon:

**Comment by hitochan777** [comment]
@sunaku Tried but not working since unless `zplug load` is run, functions from zsh-history-substring-search.zsh are not available.

**Comment by sunaku** [comment]
That's strange.  `bindkey` should run without complaints even if the target function is yet-to-be defined:

```
?master ~/.zsh/bundle/2/zsh-history-substring-search> zsh -f
yantram% bindkey '^[[A' history-substring-search-up
yantram% source zsh-history-substring-search.zsh 
yantram% key<UP>
```

**Comment by hitochan777** [comment]
If I run 
```
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```
before `zplug load`, I got the following error,
```
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-up'
zsh-syntax-highlighting: unhandled ZLE widget 'history-substring-search-down'
```

So I removed zsh-syntax-highlighting from .zshrc and the error is gone but still not working.

**Comment by Defman21** [comment]
Have you tried

```
bindkey '\eOA' history-substring-search-up
bindkey '\eOB' history-substring-search-down
``` 

It works for me.


```
### PLUGINS ###

source $HOME/.zplug/init.zsh

zplug "modules/tmux",       from:prezto
zplug "modules/history",    from:prezto
zplug "modules/utility",    from:prezto
zplug "modules/ruby",       from:prezto
zplug "modules/ssh",        from:prezto
zplug "modules/terminal",   from:prezto
zplug "modules/directory",  from:prezto
zplug "modules/completion", from:prezto

zplug "zsh-users/zsh-completions"
zplug "tarruda/zsh-autosuggestions",            nice:10
zplug "zsh-users/zsh-syntax-highlighting",      nice:11
zplug "zsh-users/zsh-history-substring-search", nice:12

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load --verbose

if zplug check zsh-users/zsh-autosuggestions; then
    ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
    ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#(up|down)-line-or-history}")
fi


KEYTIMEOUT=1
bindkey -v

if zplug check zsh-users/zsh-history-substring-search; then
    bindkey '\eOA' history-substring-search-up
    bindkey '\eOB' history-substring-search-down
fi
```

**Comment by Defman21** [comment]
Also try to bind `^A` or something and see if it works for you.

**Comment by hitochan777** [comment]
@Defman21 Thanks! 

```
bindkey '\eOA' history-substring-search-up # or ^[OA
bindkey '\eOB' history-substring-search-down # or ^[OB
```
This worked! But I don't really know why pressing UP and DOWN key in `cat -v` gives `^[[A` and `^[[B`.

**Comment by Defman21** [comment]
Nor am I. Are you using tmux by the way? This might be  problem.

**Comment by hitochan777** [comment]
I usually use `tmux`, but even if I don't use tmux, it gives me  `^[[A` and `^[[B`.
Anyways thank you very much for your help,  @Defman21 and @sunaku !

**Comment by mashehu** [comment]
I had the same problem using antigen on MacOS Sierra. `cat -v` gives `^[[A` and `^[[B`, but it only works if I use `'\eOA'` and `'\eOB'` as mentioned by @Defman21 .

**Comment by samumist** [comment]
Thanks @Defman21 
I had the same problem with `^[[A` and `^[[B`. Your solution provided above solved it.

**Comment by MissingNoIOI** [comment]
On Linux in  the other hand it only appears to work by using 

`if zplug check zsh-users/zsh-history-substring-search; then
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
fi
`

**Comment by kreedz** [comment]
Had the same issue.
You can try to type C-v in the console and then type your arrow (up or down).
So it gives me '^[OA' and '^[OB'. Only these keys work with bindkey.
Keys that give me `cat -v` ('^[[A' and '^[[B') doesn't work.

**Comment by Cerule** [comment]
I had exactly same issue on Linux & Konsole. \e0A and \e0B worked.

**Comment by sunaku** [comment]
Thanks everyone for working through this issue.  The README has been updated to note the `<C-v>` trick.
