### ISSUE TITLE
Plugins breaks if `zle -N zle-line-init` is called

### ISSUE THREAD

**Issue by molovo** [zsh-users/zsh-history-substring-search#70]
Noticed this when working with [`oz/safe-paste`](https://github.com/oz/safe-paste) and [`willghatch/zsh-hooks`](https://github.com/willghatch/zsh-hooks). If either of those plugins is sourced alongside `zsh-history-substring-search` then the `history-substring-search-up` and `history-substring-search-down` functions fail to work (both in normal usage, and when using `zsh -f` and only sourcing `zsh-history-substring-search` and the affected plugins).

Without either of those plugins it works fine. Both plugins register `zle-line-init`, and commenting out the line which registers it allows `zsh-history-substring-search` to work. Is there any way around this? It doesn't seem to matter which order the plugins are called in, the issue still occurs.

**Comment by sunaku** [comment]
I wonder if their `zle-line-init` ends up blocking the call to `history-substring-search-up`?  It might be the case that the calls to this plugin's ZLE widgets aren't going through and they are in fact okay.

**Comment by squarefrog** [comment]
In case anyone else encounters this, you can rebind the keys after `zle-line-init` and you're able to use both `history-substring-search` and whatever requires the init function.

In my [.zshrc](https://github.com/squarefrog/dotfiles/blob/1b736cd46895a00a696e73d35a0d4a1c309983cc/zsh/.zshrc) I simply `source keybindings.zsh` at the end of the file to get both `vi` status and history search working.

**Comment by molovo** [comment]
Hmm. That might be it. Im pulling keycodes out of the `terminfo` module, which reports up (`kcuu1`) as `^[0A` instead of `^[[A`. Binding `^[[A` manually mean up/down works with history-substring-search both before and after `zle-line-init`, but if I bind `$terminfo[kcuu1]` (`^[0a`), up/down only works **after** `zle-line-init`. I wonder why there's a distinction?
