### ISSUE TITLE
Whenever Zsh starts on Gentoo this plugin isn't loaded despite being in .zshrc; it is loaded after I source Zsh again

### ISSUE THREAD

**Issue by fusion809** [zsh-users/zsh-history-substring-search#77]
Hi,

On Gentoo Linux I have noticed a bug in this plugin, even though this plugin is sourced by my `~/.zshrc` file (which can be found here https://github.com/fusion809/gentoo-scripts/blob/master/.zshrc) it isn't loaded on Zsh startup, I say this as typing in a substring and pressing the up arrow doesn't cause the latest command that contains the substring to be loaded (rather just the previous command is loaded). After I run `source ~/.zshrc` again the substring search works fine. Any ideas why? On other distros this `~/.zshrc` file works fine, with this plugin loading perfectly without the need to source zshrc again.

NOTE: I also asked this question on The Gentoo Forums https://forums.gentoo.org/viewtopic-p-8054522.html#8054522.

Thanks for your time,
Brenton

**Comment by sunaku** [comment]
Perhaps your up/down key bindings are being reset/changed from using this plugin after the initial load.  Are you able to reproduce this issue under a vanilla `zsh -f` session (as shown in the screencast below)?

[![asciicast](https://asciinema.org/a/89727.png)](https://asciinema.org/a/89727)

**Comment by fusion809** [comment]
Thanks for your response, I suspected I'd just have to suck it up with respect to this error. Yep I tried in a vanilla session to load this plugin and it still isn't working for me. 

![screenshot_20170505_212036](https://cloud.githubusercontent.com/assets/4717341/25743649/ba25e4d4-31d8-11e7-9298-5cdf8646c5c5.png)

In the screenshot in the top right-hand split view of yakuake (the one with the `source zsh-history-substring-search/zsh-history-substring-search.zsh` line and then `jsh`) I typed `sour` and pressed the up arrow key and it selected `jsh` (the last command issue, which doesn't match the `sour` substring).

**Comment by fusion809** [comment]
If more info is required merely tell me what I need to give ya.

**Comment by sunaku** [comment]
From what I could gather from your screenshot, it seems you have forgotten to bind your UP/DOWN arrow keys to this plugin's ZLE widgets.  As a result, typing `sour` and then pressing UP won't invoke this plugin.

**Comment by fusion809** [comment]
Oh now it works in vanilla mode, rofl, sorry I didn't follow your little video quite right. But my `~/.zshrc` has those lines in it.

**Comment by sunaku** [comment]
I suspect that `source $ZSH/oh-my-zsh.sh` on line 81 is resetting your UP/DOWN keybindings.  Try moving those keybindings below line 81.  You can and also try adding this plugin to your `plugins` array on line 55 to get rid of the explicit source on line 57.

**Comment by fusion809** [comment]
https://gist.github.com/92d03414af726768003649f42eff6546 is what my `~/.zshrc` file looks like after trying to implement your suggestions but opening a new Zsh session causes a problem. Whenever I enter in a substring and press the up key I get this appear below the input:

```bash
No such widget `history-substring-search-up'
```

**Comment by fusion809** [comment]
Pressing up with no input (i.e., no substring to search) also causes:

```bash
No such widget `history-substring-search-up'
```

**Comment by fusion809** [comment]
Ah I fixed the issue. I did what you suggested (moving the bindings below the source `$ZSH/oh-my-zsh.zsh` line), without removing the `zsh-history-substring-search` source line and adding it into the plugins array. Here is my `~/.zshrc` now https://gist.github.com/6472c1df75296de0f2cbe9f31e6c0bc2.

**Comment by sunaku** [comment]
Glad it worked out. :smile_cat:
