### ISSUE TITLE
What are the options for HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS?

### ISSUE THREAD

**Issue by dsandstrom** [zsh-users/zsh-history-substring-search#89]
I can't find it documented anywhere.

**Comment by gezalore** [comment]
There is no such config variable in the latest.

**Comment by dsandstrom** [comment]
Sorry, I must have been looking at old docs.  I was really asking about `HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS`.

I can't get my substring searching to act like it did before and wondering if this option can help.

**Comment by gezalore** [comment]
The README says:

See the "Globbing Flags" section in the zshexpn(1) man page to learn about the kinds of values you may assign to this variable

Is that not what you are looking for?

**Comment by dsandstrom** [comment]
Thank you for the quick response.  The man pages aren't beneficial to me.  I'd like to know what the options are.

**Comment by dsandstrom** [comment]
You know what I'm making a mess of this issue, I'm going to close this and open a new one.
