### ISSUE TITLE
What are the options for HISTORY_SUBSTRING_SEARCH_FUZZY?

### ISSUE THREAD

**Issue by dsandstrom** [zsh-users/zsh-history-substring-search#90]
The docs say:

> HISTORY_SUBSTRING_SEARCH_FUZZY is a global variable that defines how the command history will be searched for your query. If set to a non-empty value, causes this script to perform a fuzzy search by words, matching in given order e.g. ab c will match *ab*c*

What are the options?

**Comment by gezalore** [comment]
Empty string, which means no fuzzy search (default):
```
HISTORY_SUBSTRING_SEARCH_FUZZY='' 
```
or any non-empty string, which makes it use fuzzy search:
```
HISTORY_SUBSTRING_SEARCH_FUZZY='whateveryouwant' 
```

**Comment by dsandstrom** [comment]
I thought the "abc" were part of the pattern, it makes sense now.
