### ISSUE TITLE
setting shwordsplit causes highlighting in wrong place after fuzzy search commit(fd27842cad08)

### ISSUE THREAD

**Issue by ratheesh** [zsh-users/zsh-history-substring-search#93]
setting `shwordsplit` causes highlighting in wrong place

**Steps:** Working case
$ cd <zsh-history-substring-search plugin source>
$ zsh -f
$ source zsh-history-substring-search.zsh
$ bindkey '^[[A' history-substring-search-up
$ bindkey '^[[B' history-substring-search-down
$ sudo apt update
$ update -> press UP key -> works fine.(highlighting highlights `update` as expected)

**Steps:** Non-working case
$ cd <zsh-history-substring-search plugin source>
$ zsh -f
$ source zsh-history-substring-search.zsh
$ bindkey '^[[A' history-substring-search-up
$ bindkey '^[[B' history-substring-search-down
$ **setopt shwordsplit**
$ sudo apt update
$ update -> press UP key -> wrong highlighting.(highlights between `do apt`)

Bisecting source pointed out to commit `fd27842cad08b07178519bf88a41aa6a8978747b`
If we reset HEAD to commit previous to this commit, setting `shwordsplit` works.

Setting `HISTORY_SUBSTRING_SEARCH_FUZZY` to zero or non-zero values did not make any difference.

Zsh version used: 5.4.2

**Comment by d10n** [comment]
Fixed in #99 ; specifically commit 36505c46c76c02ee0e9a7eb149ee555fb5ae6545

**Comment by ratheesh** [comment]
Verified and working fine.
Closing this issue.
