### ISSUE TITLE
in fuzzy mode it does't work

### ISSUE THREAD

**Issue by yukunfeng** [zsh-users/zsh-history-substring-search#94]
I set this value in .zshrc like this in my .zshrc.
 
`HISTORY_SUBSTRING_SEARCH_FUZZY='whateveryouwant'`

But no fuzzy search effect observed. E.g., I type this at first:
 
`touch abdefch.txt`
 
After this command, I type 'touch ab c' and up arrow, but no history command found.

**Comment by AtomicCoding** [comment]
+1

**Comment by yukunfeng** [comment]
@AtomicCoding oh.thank you..but it seems this trick doesn't work for me. I reset this value after my zsh loads this plugin..

**Comment by jpkempf** [comment]
Same issue here, has anyone been able to figure this out? I'm setting the variable in my `.zshrc` right after the list of plugins. Doing a manual `echo` in my terminal session confirms the value has been set, but to no effect.

**Comment by dominik-ba** [comment]
I requested an update of this plugin in oh my zsh and it got updated.
Now you should be able to simply enable history-substring-search in the plugins list (please notice the missing zsh- prefix) and add the `HISTORY_SUBSTRING_SEARCH_FUZZY` env.
For me this worked.

**Comment by soultice** [comment]
Still having this issue. The value is set but fuzzy search is not working for me.

**Comment by hariprasadiit** [comment]
that variable needs to be set after `source $ZSH/oh-my-zsh.sh`, If anyone has missed. For me that was the issue
